name: CSharp Test
on:
  push:
    paths:
    - 'csharp/**.cs'
    - 'csharp/**.csproj'
  schedule:
  - cron: '45 1 8 */3 *'
  workflow_dispatch:
jobs:
  compile:
    name: "Build C# on ${{ matrix.os }}"
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./csharp
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
        global-json-file: csharp/global.json
    - name: Build and Prove
      continue-on-error: true
      run: dotnet run -- /test
          